import type { Event } from "@/lib/types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Tech Conference 2025",
    description:
      "Join us for the biggest tech conference of the year. Learn from industry experts and network with professionals.",
    date: "2025-06-15",
    time: "9:00 AM",
    location: "San Francisco Convention Center",
    image: "/placeholder.svg?height=192&width=384&text=Tech+Conference",
    category: "Tech",
    attendees: 250,
  },
  {
    id: "2",
    title: "Community Hackathon",
    description:
      "A 48-hour hackathon where developers, designers, and entrepreneurs come together to build innovative solutions.",
    date: "2025-05-20",
    time: "10:00 AM",
    location: "Downtown Innovation Hub",
    image: "/placeholder.svg?height=192&width=384&text=Hackathon",
    category: "Tech",
    attendees: 120,
  },
  {
    id: "3",
    title: "Business Networking Mixer",
    description:
      "Expand your professional network at our monthly business mixer. Great opportunity to meet local entrepreneurs.",
    date: "2025-04-10",
    time: "6:30 PM",
    location: "Grand Hotel Rooftop",
    image: "/placeholder.svg?height=192&width=384&text=Networking",
    category: "Business",
    attendees: 85,
  },
  {
    id: "4",
    title: "Art Exhibition Opening",
    description:
      "Opening night for the new contemporary art exhibition featuring works from local and international artists.",
    date: "2025-04-05",
    time: "7:00 PM",
    location: "City Art Gallery",
    image: "/placeholder.svg?height=192&width=384&text=Art+Exhibition",
    category: "Arts",
    attendees: 110,
  },
  {
    id: "5",
    title: "Startup Pitch Night",
    description: "Watch innovative startups pitch their ideas to investors and get a chance to network with founders.",
    date: "2025-05-12",
    time: "5:00 PM",
    location: "Venture Capital Building",
    image: "/placeholder.svg?height=192&width=384&text=Pitch+Night",
    category: "Business",
    attendees: 75,
  },
  {
    id: "6",
    title: "Charity Fun Run",
    description: "5K fun run to raise funds for local charities. All fitness levels welcome. Refreshments provided.",
    date: "2025-06-01",
    time: "8:00 AM",
    location: "City Park",
    image: "/placeholder.svg?height=192&width=384&text=Fun+Run",
    category: "Social",
    attendees: 180,
  },
  {
    id: "7",
    title: "Web Development Workshop",
    description: "Learn the basics of web development in this hands-on workshop. Perfect for beginners.",
    date: "2025-04-25",
    time: "1:00 PM",
    location: "Tech Learning Center",
    image: "/placeholder.svg?height=192&width=384&text=Workshop",
    category: "Education",
    attendees: 40,
  },
  {
    id: "8",
    title: "Community Cleanup Day",
    description: "Join your neighbors in cleaning up our community. Equipment and refreshments provided.",
    date: "2025-05-05",
    time: "9:00 AM",
    location: "Community Center",
    image: "/placeholder.svg?height=192&width=384&text=Cleanup+Day",
    category: "Social",
    attendees: 65,
  },
]

